# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.drug.com:
  peer0.manufacturer.drug.com:
  peer1.manufacturer.drug.com:
  peer0.distributor.drug.com:
  peer1.distributor.drug.com:
  peer0.retailer.drug.com:
  peer1.retailer.drug.com:
  peer0.transporter.drug.com:
  peer1.transporter.drug.com:

networks:
  pharmanet3:
    name: network_pharmanet3

services:

  orderer.drug.com:
    container_name: orderer.drug.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.drug.com:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/drug.com/orderers/orderer.drug.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/drug.com/orderers/orderer.drug.com/tls/:/var/hyperledger/orderer/tls
        - orderer.drug.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 9443:9443
    networks:
      - pharmanet3

  peer0.manufacturer.drug.com:
    container_name: peer0.manufacturer.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.manufacturer.drug.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.drug.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.drug.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.drug.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.drug.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP      
      - CORE_OPERATIONS_LISTENADDRESS=peer0.manufacturer.drug.com:9444
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/manufacturer.drug.com/peers/peer0.manufacturer.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/manufacturer.drug.com/peers/peer0.manufacturer.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer0.manufacturer.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
      - "9444:9444"
    networks:
      - pharmanet3

  peer1.manufacturer.drug.com:
    container_name: peer1.manufacturer.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.manufacturer.drug.com
      - CORE_PEER_ADDRESS=peer1.manufacturer.drug.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.manufacturer.drug.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manufacturer.drug.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.drug.com:8051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.manufacturer.drug.com:9445
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/manufacturer.drug.com/peers/peer1.manufacturer.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/manufacturer.drug.com/peers/peer1.manufacturer.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer1.manufacturer.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
      - 9445:9445
    networks:
      - pharmanet3

  peer0.distributor.drug.com:
    container_name: peer0.distributor.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.distributor.drug.com
      - CORE_PEER_ADDRESS=peer0.distributor.drug.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.drug.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.drug.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.drug.com:9051
      - CORE_PEER_LOCALMSPID=distributorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.distributor.drug.com:9446
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/distributor.drug.com/peers/peer0.distributor.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/distributor.drug.com/peers/peer0.distributor.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer0.distributor.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 9446:9446
    networks:
      - pharmanet3

  peer1.distributor.drug.com:
    container_name: peer1.distributor.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.distributor.drug.com
      - CORE_PEER_ADDRESS=peer1.distributor.drug.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.distributor.drug.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.drug.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.drug.com:10051
      - CORE_PEER_LOCALMSPID=distributorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.distributor.drug.com:9447
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/distributor.drug.com/peers/peer1.distributor.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/distributor.drug.com/peers/peer1.distributor.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer1.distributor.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10051:10051
      - 9447:9447
    networks:
      - pharmanet3

  peer0.retailer.drug.com:
    container_name: peer0.retailer.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.retailer.drug.com
      - CORE_PEER_ADDRESS=peer0.retailer.drug.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.drug.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.drug.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.drug.com:11051
      - CORE_PEER_LOCALMSPID=retailerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.retailer.drug.com:9448
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/retailer.drug.com/peers/peer0.retailer.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/retailer.drug.com/peers/peer0.retailer.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer0.retailer.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
      - 9448:9448
    networks:
      - pharmanet3

  peer1.retailer.drug.com:
    container_name: peer1.retailer.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.retailer.drug.com
      - CORE_PEER_ADDRESS=peer1.retailer.drug.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailer.drug.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailer.drug.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailer.drug.com:12051
      - CORE_PEER_LOCALMSPID=retailerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.retailer.drug.com:9449
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/retailer.drug.com/peers/peer1.retailer.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/retailer.drug.com/peers/peer1.retailer.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer1.retailer.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 12051:12051
      - 9449:9449
    networks:
      - pharmanet3

  peer0.transporter.drug.com:
    container_name: peer0.transporter.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.transporter.drug.com
      - CORE_PEER_ADDRESS=peer0.transporter.drug.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.drug.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transporter.drug.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.drug.com:13051
      - CORE_PEER_LOCALMSPID=transporterMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.transporter.drug.com:9450
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/transporter.drug.com/peers/peer0.transporter.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/transporter.drug.com/peers/peer0.transporter.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer0.transporter.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 13051:13051
      - 9450:9450
    networks:
      - pharmanet3

  peer1.transporter.drug.com:
    container_name: peer1.transporter.drug.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_pharmanet3
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.transporter.drug.com
      - CORE_PEER_ADDRESS=peer1.transporter.drug.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.transporter.drug.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.transporter.drug.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.transporter.drug.com:14051
      - CORE_PEER_LOCALMSPID=transporterMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.transporter.drug.com:9451
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/transporter.drug.com/peers/peer1.transporter.drug.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/transporter.drug.com/peers/peer1.transporter.drug.com/tls:/etc/hyperledger/fabric/tls
        - peer1.transporter.drug.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 14051:14051
      - 9451:9451
    networks:
      - pharmanet3

  

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.manufacturer.drug.com
      - peer1.manufacturer.drug.com
      - peer0.distributor.drug.com
      - peer1.distributor.drug.com
      - peer0.retailer.drug.com
      - peer1.retailer.drug.com
      - peer0.transporter.drug.com
      - peer1.transporter.drug.com
    networks:
      - pharmanet3